### ISSUE TITLE
Disable Gundo deprecation

### ISSUE THREAD

**Issue by albfan** [simnalamburt/vim-mundo#53]
What about people making the transition? Seems wrong that a plugin invalidates other.

Is Gundo incompatible with Mundo in some way. If not you should about nasty things like disable other plugin

**Comment by simnalamburt** [comment]
Actually that option was added because mundo was once a fork of gundo. It had shared a name of configs and variables.

Now mundo has been diverged from gundo and renamed all variables. But still some people were using gundo's configs for mundo. The mundo maintainers (I and @dsummersl) were highly worried about making a breaking change, so we decided to preserve that variable names but make a warning at the same time.

Since there is no way to properly version a package, it's very hard to make some breaking change. If a vim package can be versioned with semver, I would just break things and move on. But with pathogen, vim-plug, and etc, we cannot.

I'm quite sure that someone will still use gundo-day's config names for mundo, so I still don't want to break their UX. Do you have any good idea?

**Comment by albfan** [comment]
I think mundo disabled gundo, but it breaks it indeed. Why not just add an option to enable compatibility? Anyway I understand troubles in separate from upstream
